default: &default
  adapter: mysql2
  user: 'root'
  password: ""
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/community_site_development

test:
  <<: *default
  database: db/community_site_test

production:
  <<: *default
  database: db/community_site_production
